### ISSUE TITLE
Use Text in Reflex demo

### ISSUE THREAD

**Issue by 3noch** [matchwood/react-vs-react-flux-vs-reflex-frp#1]
These should be using `Text`: https://github.com/matchwood/react-vs-react-flux-vs-reflex-frp/blob/master/reflex-frp/src/Main.hs#L32

**Comment by matchwood** [comment]
Hi 3noch, by 'should' I guess you mean for performance reasons? The point of this repo is to compare frameworks, not to optimise for performance per se. The original code, using `String`, is actually from a reflex repo: https://github.com/reflex-frp/reflex-huge-table/blob/master/src/Main.hs that was used to look at memory usage, and of course the flux example here also uses `String` https://github.com/matchwood/react-vs-react-flux-vs-reflex-frp/blob/master/react-flux/src/Main.hs.

But anyway, sure I'll change it over, I guess it's nicer to have a fairer comparison with pure js React.

**Comment by 3noch** [comment]
@matchwood Yah by "should" I guess I meant if you want a fairer comparison to pure JS. No one uses linked lists for strings in JS. In Haskell, any app worth its salt will use `Text` instead of `String` for almost everything. So even in the Haskell context it's common to avoid `String`. That would obviously apply to both Reflex and React bindings. Thanks for the change.
